version: '3.8'

services:
  api:
    build: .
    ports:
      - "80:80"
    environment:
      - ConnectionStrings__ConnectionStrings=Server=sqlserver;Database=YourDB;User=userapi;Password=userapi;multipleactiveresultsets=true;TrustServerCertificate=True;"
    depends_on:
      - sqlserver

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "YourPassword123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"